alias tm='tmux'
alias nv='neovim'
alias ll='ls -haltr'
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
alias ..='cd ..'
alias ...='cd ../..'
alias h='history'
alias c='clear'
alias diff='colordiff'
alias python='python3.12'
alias python3='python3.12'
alias sp='space'
alias deact='deactivate'

